sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bavjackson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bavjackson/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-081026603580"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY